version: '3'
services:
  api:
    image: rehoboam-ui-service:latest
    container_name: rehoboam-ui-service
    expose:
      - 8091
    environment:
      - VIRTUAL_HOST=rehoboamcube.com, www.rehoboamcube.com
      - VIRTUAL_PORT=8091
      - NODE_APP_INSTANCE=prod
      - LETSENCRYPT_HOST=rehoboamcube.com, www.rehoboamcube.com
      - LETSENCRYPT_EMAIL=16apterson@gmail.com

networks:
  default:
    external:
      name: nginx-proxy