version: '3'
services:
  api:
    image: rehoboam-ui-service:latest
    container_name: rehoboam-ui-service
    expose:
      - 8091
      - 60000
    environment:
      - VIRTUAL_HOST=api.rehoboamcube.com
      - VIRTUAL_PORT=8091
      - NODE_APP_INSTANCE=prod
      - LETSENCRYPT_HOST=api.rehoboamcube.com
      - LETSENCRYPT_EMAIL=16apterson@gmail.com
    networks:
      - nginx-proxy
      - rehoboam

networks:
  nginx-proxy:
    name: nginx-proxy
  rehoboam:
    name: rehoboam
# networks:
#   default:
#     external:
#       name: nginx-proxy