version: '3.7'
services:
  api:
    image: rehoboam-ui-service:latest
    container_name: rehoboam-ui-service
    expose:
      - 8091
    environment:
      - VIRTUAL_HOST=api.rehoboamcube.com
      - VIRTUAL_PORT=8091
      - NODE_APP_INSTANCE=prod
      - LETSENCRYPT_HOST=api.rehoboamcube.com
      - LETSENCRYPT_EMAIL=16apterson@gmail.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy